### ISSUE TITLE
PoiSheet reads number of columns always from the first row

### ISSUE THREAD

**Issue by dusiema** [spring-projects/spring-batch-extensions#10]
[`PoiSheet`](https://github.com/spring-projects/spring-batch-extensions/blob/master/spring-batch-excel/src/main/java/org/springframework/batch/item/excel/poi/PoiSheet.java) always reads the number of columns from the first row. 

Especially when a [`RowNumberColumnNameExtractor`](https://github.com/spring-projects/spring-batch-extensions/blob/master/spring-batch-excel/src/main/java/org/springframework/batch/item/excel/support/rowset/RowNumberColumnNameExtractor.java) is defined (with the `headerRowNumber` attribute set) it would make sense to read the number of columns from the row that has the header. 

And maybe the default should be to read the number of columns for the current row that is processed.

@mdeinum What do you think?

**Comment by mdeinum** [comment]
Well the assumption is/was that when using a header you should always have the same amount of columns for all the rows. But maybe we should take a different approach on this and differentiate between using a header and not using a header. (Maybe even add some validation).

Agree on using the number of rows from the row that actually contains the header, I guess that was an omission when creating/refactoring this class. 

Ofcourse pull requests are welcomed :).

**Comment by dusiema** [comment]
I looked into this again today. 
But I am not sure on how to implement this. 
I would like to only read the number of columns from the header row if a `RowNumberColumnNameExtractor` was set. 
But the number of columns is read from the Sheet and the sheet does not know about the column name extractor because it is set on the `AbstractExcelItemReader`.

Should I just add a property like `headerRowNumber` on the `AbstractExcelItemReader` and the propagade it through to the Sheets `getNumberOfColumns()` ?
