### ISSUE TITLE
Add support for resetting the currentSheet index to 0 upon doClose()

### ISSUE THREAD

**Issue by codelirium** [spring-projects/spring-batch-extensions#11]

**Comment by codelirium** [comment]
Hello mdeinum,

Have a look @ https://github.com/spring-projects/spring-batch-extensions/pull/14

I think there is one more state variable that needs resetting plus I updated the unit tests.

Kindest regards,
Stavros Lekkas (@codelirium)

**Comment by codelirium** [comment]
Hello @mminella, would that be possible to review and merge #14 ?

**Comment by mminella** [comment]
Why is doing this via a new instance using step scope not good enough?  I ask since that's the way just about every other reader works...

**Comment by codelirium** [comment]
I might sound weird to you but:

1) I thought reusing the same reader adds up to flexibility.
2) I did not want to create a separate reader bean tight to every additional pass I want to make to the excel file - in cases where more than one additional passes are required.

**Comment by mminella** [comment]
Do you have an example of where this approach is preferred than the step one I'm proposing?

**Comment by codelirium** [comment]
I am afraid I do not. I just felt reusing the reader in the product I rolled out last month.

**Comment by mdeinum** [comment]
Fixed in #65.
