### ISSUE TITLE
Read columns as arrays

### ISSUE THREAD

**Issue by LiveNathan** [spring-projects/spring-batch-extensions#114]
Hello! The second worksheet of every one of my workbooks has four columns with 24,000 rows. Ideally, I'd like to read in both sheets and each column needs to eventually exist as an array. Since this project converts each row to an object, is there a way to handle my case with columns to arrays?

<img width="334" alt="2023-07-06 at 09 14 48@2x" src="https://github.com/spring-projects/spring-batch-extensions/assets/60303904/49c001eb-330e-4705-b506-2789e57d6628">

**Comment by mdeinum** [comment]
We generally read rows, which are represented as an array. But you want the columns as arrays?

**Comment by mdeinum** [comment]
Excel is row oriented and so is the Apache POI library, so the only way to retrieve all values for the columns is to iterate over the rows. So I'm not sure how to approach this without pulling everything apart. 

The quickest workaround would be to create a a writer that writes to the array(s) you need, stores it somewhere (maybe in the jobcontext) then have another step operate on that array.

**Comment by LiveNathan** [comment]
Ok, thanks. That is how I'm currently handling it.
