### ISSUE TITLE
Excel file only read once - subsequent parses hang

### ISSUE THREAD

**Issue by john-london** [spring-projects/spring-batch-extensions#12]
I don't know for sure if this is an issue with this plugin, or whether it is caused by something I am doing / not doing.  Details are here: http://stackoverflow.com/questions/29127028/grails-spring-batch-excel-reader-only-reads-file-once.

When I read an XLSX file, it works the first time, but subsequent attempts to parse the same file (by restarting Grails) just mean the job continues indefinitely.  I need to reboot the computer to be able to rerun the job (and then it will only run once before hanging again).

**Comment by mdeinum** [comment]
Need more information to diagnose is. Please provide a minimal repoducing example we can run to investigate. 

For now closing the issue as it is also almost 10 years old.
