### ISSUE TITLE
Support customization of FormulaEvaluator in PoiSheet

### ISSUE THREAD

**Issue by sravaniv-3cortex** [spring-projects/spring-batch-extensions#126]
Our use case of reading Excel files requires that errors in resolving the external sheet references in formula evaluations be ignored. This requires calling the `org.apache.poi.ss.usermodel.FormulaEvaluator.setIgnoreMissingWorkbooks(boolean)`. This isn't currently possible with the current PoiSheet implementation - `PoiSheet` is package-private so it can't be extended to override the `getRow` method, which allows us to customize the `FormulaEvalutor` instance used.

What is the feasibility of doing one of these things?
- Opening up `PoiSheet` for extension
- Have a settings class which can be passed by the user and later applied by the PoiSheet to the `FormulaEvaluator`. This might result in future asks for setting classes for other things.

If nothing above works, the other option is to duplicate `PoiSheet` with necessary changes and then override `PoiItemReader`.

**Comment by mdeinum** [comment]
While working on this I wonder if it would be a sensible default to set this to `true` by default. Or maybe even take it a step further and when we encounter a formula cell to always return the cached value. As we are reading the files the cached value should, generally speaking, be the right value. We don't inline change related cells or workbooks. 

So from a performance perspective it might be even beneficial to, by default, ignore the formula(s).
