### ISSUE TITLE
Add readOnly boolean on PoiItemReader

### ISSUE THREAD

**Issue by EXAXL** [spring-projects/spring-batch-extensions#128]
Using as-is PoiItemReader implementation force to rewrite each time input file. 
Sometime you don't need it/you can not do it (in our case we can not edit a file put on a nfs).

It could be nice adding a boolean field if the workbook has to be in readOnly mode or not.
In the current implementation it is always force to false

**Comment by mdeinum** [comment]
I wonder if this wouldn't just be a sensible default in the first place. The reader should only read the file not modify it. So we could argue here that we just always should open it in read-only mode. I don't expect any problems if we do so.
