### ISSUE TITLE
Remove JXL support

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-batch-extensions#19]
since JExcelAPI is an abandoned project (no release since 2009, with serious bugs remaining).

This way we could simplify the API and remove some of the abstraction and make it dedicated for POI. We could then also consider creating an `ItemWriter` for writing out excel files instead of only reading.

**Comment by codelirium** [comment]
I can pick this up during the weekend  and provide a pull - if you have not started this already.

**Comment by mdeinum** [comment]
Feel free to create a pull request.

**Comment by codelirium** [comment]
Do you think its a good idea if we first merge pull #14 so that i wipe off the unnecessary tests too?

**Comment by mdeinum** [comment]
I'm afraid I don't have write access here so I cannot merge it. @mminella would have to be the one to merge that.

**Comment by codelirium** [comment]
Hello @mdeinum, @mminella. I have removed the JXL support. It wont allow me to create a pull as theres one pending already. You can find the changes here:

https://github.com/spring-projects/spring-batch-extensions/compare/master...codelirium:master

Let me know if you need something changed.

**Comment by mminella** [comment]
Please create this PR using a feature branch.  Then we can get both merged maintaining history.

**Comment by codelirium** [comment]
Absolutely, will do so soon.

**Comment by almex** [comment]
That's the ideaI've already followed with my own project and here is my implementation of a writer :https://github.com/almex/Raildelays/blob/master/batch/src/main/java/org/springframework/batch/item/file/ExcelSheetItemWriter.java

**Comment by mdeinum** [comment]
JXL Support removed in #65.
