### ISSUE TITLE
Use reader current row count from failed execution to get correct row on restart

### ISSUE THREAD

**Issue by scloutier** [spring-projects/spring-batch-extensions#25]
I noticed when restarting jobs after failure, the `AbstractExcelItemReader` would begin reading from the first row in the spreadsheet. The `doRead` method is simply calling `rowSet.next()` and ignoring the `AbstractItemCountingItemStreamItemReaders` attempt to jump to the correct row. A solution that I found to work was to override the `jumpToItem` method in `AbstractExcelItemReader` and simply call `rowSet.next` until we have the correct row.

**Comment by mdeinum** [comment]
The `jumpToItem` method has been implemented akin the suggested solution here and inspired from the `FlatFileItemReader` from Spring Batch itself. 

Closed with #65.
