### ISSUE TITLE
spring batch unknown table unknown-table-batch-job-seq-in-field-list

### ISSUE THREAD

**Issue by bclicn** [spring-projects/spring-batch-extensions#36]
The problem is described in [this stackoverflow thread](http://stackoverflow.com/questions/34652631/unknown-table-batch-job-seq-in-field-list), can anyone give a suggestion as soon as possible? thx!

**Comment by benas** [comment]
This seems outdated and shouldn't have been opened against this repository. If you still have the problem with the latest version, please open an issue against [Spring Batch's issue tracker](https://github.com/spring-projects/spring-batch/issues).
