### ISSUE TITLE
skip a column

### ISSUE THREAD

**Issue by inarmag** [spring-projects/spring-batch-extensions#40]
Hey, 
is there any method to skip the first column of an excel file while reading it in the batch ?
thank you

**Comment by parikshitdutta** [comment]
Hi @benas,
Please have a look at PR #64, I will look forward to your feedback.

Thank you.
+ @mminella

**Comment by mdeinum** [comment]
Closed in favour of pull-request #64

**Comment by mdeinum** [comment]
Closed in favour of pull-request #64
