### ISSUE TITLE
Parsing #NA fields within excel sheet

### ISSUE THREAD

**Issue by cr0mbly** [spring-projects/spring-batch-extensions#43]
At the moment the switch case dealing with the various data does not support invalid fields. this is an issue with data sets that are generated incorrectly meaning the whole sheet is unable to be parsed if one field is out. At the moment it returns 

`Cannot handle cells of type 5` for these fields. are we able to add a switch to support these type.

this is the field type I'm referring 

![image](https://user-images.githubusercontent.com/6813352/32512365-a7443c88-c45b-11e7-85cb-64dfc0045857.png)

**Comment by waasikhaan** [comment]
@cr0mbly, How can you parse an invalid file? Don't you think you need to sort it out first before parsing it? I think this message is fine as far as the processing is concerned. 

What is your opinion @mdeinum?

**Comment by IRasmivan** [comment]
I am not sure if this is part of the same issue!


I am reading excel sheet using mapRow.

My Excel sheet has a cell containing a value #N/A. When I read the excel sheet using mapRow, The row containing #N/A values is totally skipped!

Is there any workaround to read the skipped row using RowMapper?

@Component
public class ExcelRowMapper implements RowMapper<LineItemDTO> {
@Override
@SuppressWarnings("squid:S3776")
public LineItemDTO mapRow(RowSet rs) throws Exception {
        rs.getCurrentRowIndex();
 }
}
Excel Data: 
Column Name
123123
123ss
dafsdf
#N/A
asdasd
2323

The code read first 4 rows and skipped the row containing #N/A and read the row's below.

**Comment by mdeinum** [comment]
There have been some changes to the `PoiItemReader` and it should now properly read those rows, it will show the textual representation of the error. So the cell should read `#N/A` as text. Please try with the latest versions and if this is still an error could you provide a sample Excel file that we could then use to reproduce (an Excel file with a test would even be better).

**Comment by mdeinum** [comment]
There have been changes to how rows are parsed, more of the internals of Apache POI are now used and empty rows and cells will be parsed correctly.
