### ISSUE TITLE
maven group is incorrect

### ISSUE THREAD

**Issue by tartur** [spring-projects/spring-batch-extensions#47]
springframewor instead of springframework

https://github.com/spring-projects/spring-batch-extensions/blob/6e6f2dc70370d988e8caf09703931c46db32fe99/spring-batch-elasticsearch/pom.xml#L5

**Comment by benas** [comment]
Thank you for reporting this. The groupId has been fixed in 6a06f29a36982293af0fbf6772c5b6d9caa1612e.
