### ISSUE TITLE
Exception when running in Async

### ISSUE THREAD

**Issue by gauravabburi** [spring-projects/spring-batch-extensions#48]
Hi,
When I am running the job (PoiItemReader) using Simple Async Executor, I am getting the following exception -
Exception parsing Excel file (Because of null rows)
Whereas if I run the job normally (without SimpleAsyncTaskExecutor), I do not get any exceptions.

What could be the issue? Can someone help me out here?

**Comment by mdeinum** [comment]
The underlying Apache POI reader isn't thread-safe, so running this multithreaded is currently not possible due to limitations in the underlying framework as well as the fact that the `AbstractItemCountingItemStreamItemReader` isn't thread-safe either.

**Comment by mdeinum** [comment]
As both Apache POI and `AbstractItemCountingItemStreamItemReader` aren't thread-safe add a note about this as well as multiple threads in the documentation.
