### ISSUE TITLE
Lines To skip not working properly

### ISSUE THREAD

**Issue by naabbas** [spring-projects/spring-batch-extensions#56]
For POI Item Reader API if initial rows are null and we have applied linesToSkip it will skip those many lines but once it finds rows with not null values it will pick number of columns from row 0. Which should not be the case . It should pick that row column numbers.

//PoiSheet
   @Override
    public int getNumberOfColumns() {
        if (numberOfColumns < 0) {
            numberOfColumns = **this.delegate.getRow(0).getLastCellNum();**
        }
        return numberOfColumns;
    }

**Comment by mdeinum** [comment]
This code has been removed since and we always use the current row to determine the column count. Closing this as it became obsolete. 

Closed with #65.
