### ISSUE TITLE
Release spring-batch-excel version 0.1.0

### ISSUE THREAD

**Issue by benas** [spring-projects/spring-batch-extensions#66]
@mdeinum Please add a comment here when the module is ready for a release. 

Please note that we are reviewing the internal release process within the entire portfolio, so I will add an update here when the release is done.

**Comment by mdeinum** [comment]
Let's see if we can get a release out and gather some input for the next version. 

There are some open tickets still, but for those, I need more input which hasn't been given yet. So we could later either defer them or decide what to do.

**Comment by benas** [comment]
Hi @mdeinum ,

Ok, I will release v0.1.0 to Maven Central and close this issue when done.

**Comment by benas** [comment]
spring-batch-excel v0.1.0 has been released to [Maven Central](https://repo1.maven.org/maven2/org/springframework/batch/extensions/spring-batch-excel/0.1.0/). I took the opportunity to upgrade Spring Batch version to the latest 4.3.3.

Congrats @mdeinum on this first release! I will let you create your initial release notes [here](https://github.com/spring-projects/spring-batch-extensions/releases).
