### ISSUE TITLE
Release spring-batch-bigquery version 0.1.0

### ISSUE THREAD

**Issue by benas** [spring-projects/spring-batch-extensions#68]
@dgray16 Please add a comment here when the module is ready for a release.

Please note that we are reviewing the internal release process within the entire portfolio, so I will add an update here when the release is done.

**Comment by dgray16** [comment]
@benas It is done

**Comment by benas** [comment]
Thank you for the updates. I will close this issue when the module is released to Maven Central.

**Comment by benas** [comment]
Done.
