### ISSUE TITLE
Publish Spring Batch Excel 0.1.1 artifacts to maven

### ISSUE THREAD

**Issue by sergeyKogan** [spring-projects/spring-batch-extensions#91]
Could you please publish the latest version to the maven repo? 
I am using the excel extension in one of my projects and I am facing an issue that was fixed in #90 however, the latest version in maven 0.1.0 does not contain the fix. 

Thanks!

**Comment by mdeinum** [comment]
The issue has been fixed in the latest snapshots, there isn't a release yet. I was also trying to shoehorn some other fix in. Which has been done. I'll request a release of the 0.1.1 binaries to maven.

**Comment by mdeinum** [comment]
Scheduled for week 17.

**Comment by benas** [comment]
The 0.1.1 artifacts have been published to Maven Central: https://repo.maven.apache.org/maven2/org/springframework/batch/extensions/spring-batch-excel/0.1.1/.

Congrats on the release!
