### ISSUE TITLE
AbstractExcelItemReader ignores a number of empty rows inbetween filled set of rows.It would help if the this functioning is made configurable since this causes incorrect meta data provided for the row number.

### ISSUE THREAD

**Issue by sr9112** [spring-projects/spring-batch-extensions#96]
`AbstractExcelItemReader` ignores a number of empty rows in between filled set of rows. It would help if the this functioning is made configurable since this causes incorrect meta data provided for the row number. 
Issue Description:
Suppose  5 rows containing data which 6th and 7th row is empty and the last 8th row has data(Screenshot attached for reference). This would return the 8th row as the 6th which may be problem if exact row number from cell is to be determined.

![image](https://user-images.githubusercontent.com/42946636/172241634-2222a580-13bc-429a-ac0d-3b88b15aafc1.png)

**Comment by mdeinum** [comment]
Could you elaborate a bit more on the issue and especially which row number/count you are referring to?

**Comment by mdeinum** [comment]
Closed due to inactivity.
