### ISSUE TITLE
Not able to open excel files larger than 10MB

### ISSUE THREAD

**Issue by quaso** [spring-projects/spring-batch-extensions#97]
When trying to read excel file larger than 10MB, an error occurs:
```
"Unexpected error Tried to allocate an array of length 162,386,364, but the maximum length for this record type is 100,000,000. If the file is not corrupt or large, please open an issue on bugzilla to request increasing the maximum allowable size for this record type. As a temporary workaround, consider setting a higher override value with IOUtils.setByteArrayMaxOverride()"
```

**Comment by mdeinum** [comment]
Thank you for using this library and for taking the time to register an issue. Could you provide a sample project (preferably a test) so that we can reproduce this?

**Comment by quaso** [comment]
I do not have any test nor sample project ready, but it is just about using StreamingXlsxItemReader with Excel file >10MB

**Comment by mdeinum** [comment]
Could you take some time to prepare a test project? You know what you've done to do this, when I try to setup a test it might not work due to differences in file, test etc. etc. So please take some time to make this into a test. You can share the repo or the project as a zip with this ticket.

**Comment by mdeinum** [comment]
I did a quick test with a 50Mb test file and I had no issues reading it. 14 columns of data with 500000 rows. So without a sample or test to reproduce this I'm afraid I have no clue on where to look for fixing this.

**Comment by mdeinum** [comment]
A start would be to add the **full stacktrace** to this thread instead of only the message, that might clear some things up. I did some quick googling and do you have an XLSX with large text blocks in them? That appears to be an known issue inside Apache POI?!
